server:
  port: 8093
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser
# http://localhost:8091/h2-console
# Enabling H2 Console
spring:

  application:
    name: profeco-service

    cloud:
      config:
        enabled: false

  sql.init.mode: always

  h2:
    console:
      enabled: true
    # ========================
    # DB
    # ========================
    datasource:
      url: jdbc:h2:mem:profecoDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      platform: h2
      username: sa
      password:

  # =====================
  # JPA / HIBERNATE
  # =====================
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show-sql: true
        use_sql_comments: false
        format_sql: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"