#Application Configuration
server:
  port: 8081

spring:
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  resources: # Static resources
    static-locations: file:src/main/resources/static/
    cache:
      period: 0

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 130130818585-r07p6fkfpsvot6v6ishi1gfue9vl0klt.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile