server:
  port: 8090
  error:
    include-message: always
    include-binding-errors: always

spring:
  ldap:
    embedded:
      port: 389
      ldif: classpath:ldap-data.ldif
      base-dn: dc=profeco,dc=org
      validation:
        enabled: false
      credential:
          username: uid=admin
          password: secret
